### ISSUE TITLE
NatCoder Unity Plugin for Linux

### ISSUE THREAD

**Issue by NinjaaSamurai** [olokobayusuf/NatCorder-Docs#1]
Hi,
    I need to record audio/video of gameplay in a standalone linux game made in unity. I had seen that Natcoder supports recording Video/Audio as mp4 in Windows/MacOs standalone app. Does it also support linux standalone app.

Thanks

**Comment by olokobayusuf** [comment]
Hi there. NatCorder currently doesn't support Linux, but we will consider adding support. I'm closing this issue.
